### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Iamtheoldman** [raine-works/sunroof-api#3]
npm WARN deprecated puppeteer@9.1.1: < 19.4.0 is no longer supported

**Comment by NishikantaRay** [comment]
npm install puppeteer@latest

**Comment by raine-works** [comment]
This has been addressed in 3ba046659a062dc5195199d46fbc54197110a267

**Comment by raine-works** [comment]
This has been addressed in 3ba046659a062dc5195199d46fbc54197110a267
